apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-yfq4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-from-registry-rh-io-yfq4
    app.kubernetes.io/part-of: test-app-869
  name: e2e-tests-parent-image-from-registry-rh-io-yfq4
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-yfq4
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-from-registry-rh-io-yfq4
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-869/e2e-tests-parent-image-from-registry-rh-io-yfq4@sha256:cabf519adfebb2fc99f11c5587eeee82c2cdd6ea4d06e2b6d63c16c5d8cae8c1
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
