apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pip-e2e-test-whnc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pip-e2e-test-whnc
    app.kubernetes.io/part-of: test-app-869
  name: pip-e2e-test-whnc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: pip-e2e-test
      app.kubernetes.io/instance: pip-e2e-test-whnc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pip-e2e-test
        app.kubernetes.io/instance: pip-e2e-test-whnc
    spec:
      containers:
      - image: pip-e2e-test:latest
        name: pip-e2e-test
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
