apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-vpx5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-vpx5
    app.kubernetes.io/part-of: test-app-869
  name: retrodep-vpx5
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-vpx5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-vpx5
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-869/retrodep-vpx5@sha256:1500866a24403e74a16874888a138b42b6e9443792b54e2597fc02d6c3f827f6
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
