apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: fbc-sample-repo-ejia
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: fbc-sample-repo-ejia
    app.kubernetes.io/part-of: test-app-869
  name: fbc-sample-repo-ejia
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: fbc
      app.kubernetes.io/instance: fbc-sample-repo-ejia
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: fbc
        app.kubernetes.io/instance: fbc-sample-repo-ejia
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-869/fbc-sample-repo-ejia@sha256:ca871e7220ac529c03ef3cc7a1adf53cceddb25c8e380b78413f81b02bab82dc
        name: fbc
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 512Mi
status: {}
