apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-juus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2e-tests-parent-image-with-digest-only-juus
    app.kubernetes.io/part-of: test-app-869
  name: e2e-tests-parent-image-with-digest-only-juus
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-juus
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: e2e-tests-parent-image-with-digest-only-juus
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-869/e2e-tests-parent-image-with-digest-only-juus@sha256:ba72425993ae7d35aaa49476775f73b5ded6db7dc0798bcabd4ec7fb85b90c0b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8081
        resources: {}
status: {}
