apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-vpbo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-vpbo
    app.kubernetes.io/part-of: test-app-869
  name: maven-hello-world-vpbo
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-vpbo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-vpbo
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-869/maven-hello-world-vpbo@sha256:04add0d1cce17a38904d945a2515efb175e67494d8efe6a89a9e3a65cf4c7c96
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
